name: omnichatai
description: OmniChat AI – Unlimited all-in-one chatbot and app builder
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  image_picker: ^0.8.6
  flutter_tts: ^3.6.3
  sqflite: ^2.2.8
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter